services:
  app:
    build: .
    # Map container port 5173 to host port 5173
    ports:
      - "5173:5173"
    # Mount your local code for hot reloading during development
    volumes:
      - .:/app
      - /app/node_modules # Prevent host's node_modules from overwriting container's
    environment:
      NODE_ENV: production
    # Use the restart policy as desired
    restart: unless-stopped